### ISSUE TITLE
🛠️ [TASK] : Research web workers to allow catalyst_compression to move it's work off the main thread

### ISSUE THREAD

**Issue by dtscalac** [input-output-hk/catalyst-voices#972]
### Summary

Research web workers to allow catalyst_compression to move it's work off the main thread

### Description

Running the catalyst_compression in a flutter web app causes visual glitches like lags to happen when compressing the data (circular progress indicator inside the button at 3s has a lag):

https://github.com/user-attachments/assets/85699529-ccbc-4b8f-8fcb-e86ed19d4896

This happens because catalyst_compression which is a Flutter wrapper around JavaScript libraries runs it's code on the main thread, the same that is used by Flutter to draw the UI and run the animations. Research and implement a solution to move this code to run in a service worker:
![Screenshot 2024-10-07 at 13 34 32](https://github.com/user-attachments/assets/753e0d51-a109-4dcc-840d-635938fb2138)

Resources:
- Flutter multithreading on web: https://docs.flutter.dev/perf/isolates#web-platforms-and-compute
- Service workers: https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API

**Comment by apskhem** [comment]
In order to achieve web worker logic with the those compression functions, we need to turn the `catalyst_voices_packages/catalyst_compression/catalyst_compression_web/assets/js/catalyst_compression.js` file into `WorkerGlobalScope` environment as shown below:

```js
import('https://unpkg.com/brotli-wasm@3.0.0/index.web.js?module').then(m => m.default).then(async (brotliModule) => {
  const brotli = brotliModule;
  const zstd = await import('https://unpkg.com/@oneidentity/zstd-js@1.0.3/wasm/index.js?module');

  await zstd.ZstdInit();

  function _brotliCompress(bytesHex) {
      const bytes = _hexStringToUint8Array(bytesHex);
      const compressedBytes = brotli.compress(bytes);
      return _uint8ArrayToHexString(compressedBytes);
  }

  function _brotliDecompress(bytesHex) {
      const bytes = _hexStringToUint8Array(bytesHex);
      const decompressedBytes = brotli.decompress(bytes);
      return _uint8ArrayToHexString(decompressedBytes);
  }

  function _zstdCompress(bytesHex) {
      const bytes = _hexStringToUint8Array(bytesHex);
      const compressedBytes = zstd.ZstdSimple.compress(bytes);
      return _uint8ArrayToHexString(compressedBytes);
  }

  function _zstdDecompress(bytesHex) {
      const bytes = _hexStringToUint8Array(bytesHex);
      const decompressedBytes = zstd.ZstdSimple.decompress(bytes);
      return _uint8ArrayToHexString(decompressedBytes);
  }

  function _hexStringToUint8Array(hexString) {
      if (hexString.length % 2 !== 0) {
          throw new Error('Invalid hex string');
      }
      const byteArray = new Uint8Array(hexString.length / 2);
      for (let i = 0; i < hexString.length; i += 2) {
          byteArray[i / 2] = parseInt(hexString.substr(i, 2), 16);
      }
      return byteArray;
  }

  function _uint8ArrayToHexString(uint8Array) {
      return Array.from(uint8Array)
          .map(byte => byte.toString(16).padStart(2, '0'))
          .join('');
  }

  const catalyst_compression = {
      brotliCompress: _brotliCompress,
      brotliDecompress: _brotliDecompress,
      zstdCompress: _zstdCompress,
      zstdDecompress: _zstdDecompress,
  };

  self.onmessage = function(event) {
      const { action, bytesHex } = event.data;
      if (catalyst_compression[action]) {
          try {
              const result = catalyst_compression[action](bytesHex);
              self.postMessage({ success: true, result });
          } catch (error) {
              self.postMessage({ success: false, error: error.message });
          }
      } else {
          self.postMessage({ success: false, error: 'Unknown action' });
      }
  };

  self.postMessage({ success: true, initialized: true });
}).catch(error => {
  self.postMessage({ success: false, error: `Failed to load modules: ${error.message}` });
});
```

This is a standalone JS file (no need to import this file into `index.html`).
Can change the file name to `catalyst_compression_worker.js`, something like this.

All the logics stay the same, except that we need to expose message sending mechanism between web workers and the main thread with `self.onmessage` and `self.postMessage`. At this point, we run the compression logic inside a web worker.

To import this `catalyst_compression_worker.js` web worker, we need another JS file to work and call this web worker:

```js
const compressionWorker = new Worker('/catalyst_voices_packages/catalyst_compression/catalyst_compression_web/assets/js/catalyst_compression_worker.js');

function _brotliCompress(data) {
  return new Promise((resolve, reject) => {
    compressionWorker.onmessage = (event) {
      const { result } = event.data;
      resolve(result);
    };

    compressionWorker.onerror = (err) {
      reject(err);
    };

    compressionWorker.postMessage({ action: 'brotliCompress', bytesHex: data });
  });
}

const catalyst_compression = {
    brotliCompress: _brotliCompress,
}

window.catalyst_compression = catalyst_compression;
```

Or we can isolate the `compressionWorker` without preinitializing in the global scope.

```js
function _brotliCompress(data) {
  return new Promise((resolve, reject) => {
    const compressionWorker = new Worker('/catalyst_voices_packages/catalyst_compression/catalyst_compression_web/assets/js/catalyst_compression_worker.js');

    compressionWorker.onmessage = (event) {
      const { result, initialized } = event.data;
      if (initialized) {
        compressionWorker.postMessage({ action: 'brotliCompress', bytesHex: data });
      } else {
        resolve(result);
        compressionWorker.terminate()
      }
    };

    worker.onerror = (error) {
      reject(error);
      compressionWorker.terminate()
    };
  });
}

const catalyst_compression = {
    brotliCompress: _brotliCompress,
}

window.catalyst_compression = catalyst_compression;
```

For the second approach, every time, when we call the function, it will need to initialize itself every time. But it could prevent unexpected behavior (because of the shared worker) in case of calling the compression functions simultaneously (not step-by-step).

<img width="306" alt="Screenshot 2024-10-16 at 19 35 12" src="https://github.com/user-attachments/assets/1dd41eea-7dea-456c-acee-deb8e65b5cb3">
initialize itself every time.

To call the compression functions that wrapped with a web worker, you can call the function as normal. But since the function return the result in `Promise<T>`, You will need to always put `await` in front of the function.

**Comment by apskhem** [comment]
Yeah, sure. I'll create a ticket for this issue then. I think everything is ready inside this ticket for implementation.

**Comment by minikin** [comment]
@apskhem, great stuff! 
My only suggestion is to make the implementation abstract and not specific to some operations.
